# Rust CLI Documentation Fine-Tuning Configuration
# Per RCDC-SPEC-001 Section 9.2

model:
  # In production: path to Qwen2.5-Coder-7B weights
  path: ./demo_model.safetensors
  layers:
    - q_proj
    - k_proj
    - v_proj
    - o_proj

data:
  train: ./data/corpus/train_numeric.parquet
  batch_size: 4
  seq_len: 512
  auto_infer_types: true

optimizer:
  name: adamw
  lr: 0.0002
  weight_decay: 0.01

lora:
  rank: 8
  alpha: 16.0
  target_modules:
    - q_proj
    - k_proj
    - v_proj
    - o_proj
  dropout: 0.05

training:
  epochs: 3
  grad_clip: 1.0
  log_interval: 10
